export const BANDERAS: Record<string, string> = {
  'México': '🇲🇽',
  'Sudáfrica': '🇿🇦',
  'Corea del Sur': '🇰🇷',
  'Rep. Checa': '🇨🇿',
  'Canadá': '🇨🇦',
  'Bosnia': '🇧🇦',
  'Qatar': '🇶🇦',
  'Suiza': '🇨🇭',
  'Estados Unidos': '🇺🇸',
  'Paraguay': '🇵🇾',
  'Australia': '🇦🇺',
  'Turquía': '🇹🇷',
  'Brasil': '🇧🇷',
  'Marruecos': '🇲🇦',
  'Haití': '🇭🇹',
  'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Alemania': '🇩🇪',
  'Ecuador': '🇪🇨',
  'Costa de Marfil': '🇨🇮',
  'Curazao': '🇨🇼',
  'Países Bajos': '🇳🇱',
  'Japón': '🇯🇵',
  'Suecia': '🇸🇪',
  'Túnez': '🇹🇳',
  'España': '🇪🇸',
  'Uruguay': '🇺🇾',
  'Arabia Saudita': '🇸🇦',
  'Cabo Verde': '🇨🇻',
  'Bélgica': '🇧🇪',
  'Egipto': '🇪🇬',
  'Irán': '🇮🇷',
  'Nueva Zelanda': '🇳🇿',
  'Francia': '🇫🇷',
  'Senegal': '🇸🇳',
  'Noruega': '🇳🇴',
  'Irak': '🇮🇶',
  'Argentina': '🇦🇷',
  'Argelia': '🇩🇿',
  'Austria': '🇦🇹',
  'Jordania': '🇯🇴',
  'Portugal': '🇵🇹',
  'Colombia': '🇨🇴',
  'Uzbekistán': '🇺🇿',
  'Rep. D. Congo': '🇨🇩',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Croacia': '🇭🇷',
  'Ghana': '🇬🇭',
  'Panamá': '🇵🇦',
}

export function bandera(equipo: string): string {
  return BANDERAS[equipo] || '🏳️'
}
